### ISSUE TITLE
custom added properties are removed 

### ISSUE THREAD

**Issue by Kailash-dev** [alimozdemir/fabric-history#35]
plugin should sustain the custom added properties by the user or developer in the fabric object

**Comment by rolitter** [comment]
init fabirc and add extraProps
```
const customProp = ['selected', 'id', 'custom',...]
new fabric.Canvas('canvas', {
  extraProps: customProp
})
```

**Comment by remorses** [comment]
Actually, you need to add `extraProps` after initialization because of this line
https://github.com/alimozdemir/fabric-history/blob/8c223cbdc8305307b4a8f8710f97da54d9146ffa/src/index.js#L49

You have to do something like this
```ts

const canvas = new fabric.Canvas('canvas', {
})
// selectable is required by this plugin
canvas.extraProps = ["selectable", "name", "id"]
```
