### ISSUE TITLE
Insufficient Granularity of Access Control in JSDom - https://github.com/advisories/GHSA-f4c9-cqv8-9v98

### ISSUE THREAD

**Issue by Talb2005** [alimozdemir/fabric-history#40]
fabric-history depends on an old version of `"fabric": "^3.3.2"`, which depends on an old version of `"jsdom": "^15.1.0"`, which has a vulnurability advisory: [Insufficient Granularity of Access Control in JSDom](https://github.com/advisories/GHSA-f4c9-cqv8-9v98)
Need to fix so that jsdom version is  >= 16.5.

**Comment by alimozdemir** [comment]
Thank you for the heads up. I will update it!

**Comment by alimozdemir** [comment]
I have updated the package (1.7.0), there is no security issue anymore.
